=== blw-ofag-ufag/data-catalog/data/schemas/dataset.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Dataset Metadata Schema",
    "type": "object",
    "properties": {
      "dcterms:identifier": {
        "type": "string"
      },
      "dcterms:title": {
        "type": "object",
        "properties": {
          "de": { "type": "string" },
          "fr": { "type": "string" }
        },
        "required": ["de", "fr"]
      },
      "dcterms:description": {
        "type": "object",
        "properties": {
          "de": { "type": "string" },
          "fr": { "type": "string" }
        },
        "required": ["de", "fr"]
      },
      "dcterms:issued": {
        "type": "string",
        "format": "date"
      },
      "dcat:keyword": {
        "type": "array",
        "items": { "type": "string" }
      },
      "bv:personalData": {
        "type": "string"
      },
      "bv:affiliatedPersons": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "bv:adminDirID": { "type": "string" },
            "role": { "type": "string" }
          },
          "required": ["bv:adminDirID", "role"]
        }
      },
      "dcat:distribution": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "dcterms:title": {
              "type": "object",
              "properties": {
                "de": { "type": "string" },
                "fr": { "type": "string" }
              },
              "required": ["de", "fr"]
            },
            "dcterms:description": {
              "type": "object",
              "properties": {
                "de": { "type": "string" },
                "fr": { "type": "string" }
              },
              "required": ["de", "fr"]
            },
            "dcat:accessURL": {
              "type": "string",
              "format": "uri"
            },
            "dcterms:format": {
              "type": "string"
            }
          },
          "required": [
            "dcterms:title",
            "dcterms:description",
            "dcat:accessURL",
            "dcterms:format"
          ]
        }
      },
      "bv:imageURL": {
        "type": "string",
        "format": "uri"
      }
    },
    "required": [
      "dcterms:identifier",
      "dcterms:title",
      "dcterms:description",
      "dcterms:issued",
      "dcat:keyword",
      "bv:personalData",
      "bv:affiliatedPersons",
      "dcat:distribution",
      "bv:imageURL"
    ]
  }

=== blw-ofag-ufag/data-catalog/data/000001.json
{
    "dcterms:identifier": "000001",
    "dcterms:title": {
        "de": "Massnahmenmonitoring Klimastrategie Landwirtschaft und Ernährung",
        "fr": "Suivi des mesures Stratégie Climat pour l'agriculture et l'alimentation"
    },
    "dcterms:description": {
        "de": "Daten zur Massnahmenumsetzung geben einen Überblick zum Umsetzungsstand der 42 Massnahmen bezüglich Klimastrategie Landwirtschaft und Ernährung. Dieser Massnahmenplan läuft bis 2030.",
        "fr": "Les données relatives à la mise en œuvre des mesures donnent un aperçu de l'état de mise en œuvre des 42 mesures relatives à la stratégie climat pour l'agriculture et l'alimentation. Ce plan de mesures court jusqu'en 2030."
    },
    "dcterms:issued": "2024-12-04",
    "dcat:keyword": [
        "environment",
        "sustainability",
        "climate",
        "monitoring",
        "food"
    ],
    "bv:personalData": "none",
    "bv:affiliatedPersons": [
        {
            "bv:adminDirID": "p-1Y4L0Y450",
            "role": "dataOwner"
        }
    ],
    "dcat:distribution": [
        {
            "dcterms:title": {
                "de": "Tabelle Massnahmenmonitoring",
                "fr": "Tableau de suivi des mesures"
            },
            "dcterms:description": {
                "de": "Excel-Tabelle mit den eigentlichen Daten zum Umsetzungsstand der 42 Massnahmen bezüglich Klimastrategie Landwirtschaft und Ernährung.",
                "fr": "Tableau Excel contenant les données réelles sur l'état d'avancement des 42 mesures relatives à la stratégie climat pour l'agriculture et l'alimentation."
            },
            "dcat:accessURL": "https://object.gever.admin.ch:443/web/?ObjectToOpenID=%24ActaNovaDocument%7C574FDB97-8106-4294-94C3-8A121A593B9E&TenantID=123",
            "dcterms:format": "XSLX"
        },
        {
            "dcterms:title": {
                "de": "PowerBI Report für das Massnahmenmonitoring",
                "fr": "Rapport PowerBI pour le suivi des mesures"
            },
            "dcterms:description": {
                "de": "Interaktiver PowerBI-Report, welcher einen Überblick zum Umsetzungsstand der 42 Massnahmen bezüglich Klimastrategie Landwirtschaft und Ernährung gibt.",
                "fr": "Rapport PowerBI interactif donnant un aperçu de l'état d'avancement des 42 mesures relatives à la stratégie climat pour l'agriculture et l'alimentation."
            },
            "dcat:accessURL": "https://www.blw.admin.ch/de/klimastrategie-landwirtschaft-und-ernaehrung-2050#%C3%9Cberpr%C3%BCfung-der-Massnahmen-und-Zielerreichung",
            "dcterms:format": "PowerBI Report"
        }
    ],
    "bv:imageURL": "https://raw.githubusercontent.com/blw-ofag-ufag/data-catalog/refs/heads/main/docs/assets/images/wetland-001.jpg"
}

=== blw-ofag-ufag/data-catalog/data/datasets/000002.json
{
    "dcterms:identifier": "000002",
    "dcterms:title": {
        "de": "Marktzahlen Eier - Jährliche Importmengen",
        "fr": "Chiffres du marché des œufs - Quantités importées annuelles"
    },
    "dcterms:description": {
        "de": "Jährliche Mengenangaben für importierte Eiprodukte und Eier auf Wertschöpfungsstufe Verarbeitung und Konsum",
        "fr": "Quantités annuelles en millions d'œufs importés à l’échelon de création de valeur transformation et consommation"
    },
    "dcterms:issued": "2025-01-16",
    "dcat:keyword": [
        "market-data",
        "quantity",
        "eggs"
    ],
    "bv:personalData": "none",
    "bv:affiliatedPersons": [
        {
            "bv:adminDirID": "p-3966584",
            "role": "dataOwner"
        },
        {
            "bv:adminDirID": "p-2713578",
            "role": "dataSteward"
        },
        {
            "bv:adminDirID": "p-1ZBQBWTM0",
            "role": "dataCustodian"
        }
    ],
    "dcat:distribution": [
        {
            "dcterms:title": {
                "de": "Tabelle Massnahmenmonitoring",
                "fr": "Tableau de suivi des mesures"
            },
            "dcterms:description": {
                "de": "Excel-Tabelle mit den eigentlichen Daten zum Umsetzungsstand der 42 Massnahmen bezüglich Klimastrategie Landwirtschaft und Ernährung.",
                "fr": "Tableau Excel contenant les données réelles sur l'état d'avancement des 42 mesures relatives à la stratégie climat pour l'agriculture et l'alimentation."
            },
            "dcat:accessURL": "https://object.gever.admin.ch:443/web/?ObjectToOpenID=%24ActaNovaDocument%7C574FDB97-8106-4294-94C3-8A121A593B9E&TenantID=123",
            "dcterms:format": "XSLX"
        },
        {
            "dcterms:title": {
                "de": "PowerBI Report für das Massnahmenmonitoring",
                "fr": "Rapport PowerBI pour le suivi des mesures"
            },
            "dcterms:description": {
                "de": "Interaktiver PowerBI-Report, welcher einen Überblick zum Umsetzungsstand der 42 Massnahmen bezüglich Klimastrategie Landwirtschaft und Ernährung gibt.",
                "fr": "Rapport PowerBI interactif donnant un aperçu de l'état d'avancement des 42 mesures relatives à la stratégie climat pour l'agriculture et l'alimentation."
            },
            "dcat:accessURL": "https://www.blw.admin.ch/de/klimastrategie-landwirtschaft-und-ernaehrung-2050#%C3%9Cberpr%C3%BCfung-der-Massnahmen-und-Zielerreichung",
            "dcterms:format": "PowerBI Report"
        }
    ],
    "bv:imageURL": "https://raw.githubusercontent.com/blw-ofag-ufag/data-catalog/refs/heads/main/docs/assets/images/eggs-001.jpg"
}
